language: go

env:
- WASMEXEC=build/tsl.wasm  

go:
- 1.12.x

go_import_path: github.com/ovh/tsl

before_script:
- mkdir build
- go get -u github.com/golang/dep/cmd/dep
- make dep

script:
- make wasm

# create npm package
after_success:
- cp wasm/index.js build
- cp wasm/package.json build
- cp $(go env GOROOT)/misc/wasm/wasm_exec.js build/wasm_exec.js
# npm publish
- ls build
